import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';

import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"

import NavigationFrame from "@/components/navigation";
import Footer from "@/components/footer"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
      <body className="relative min-h-screen bg-background">
        {/* Background Image Overlay */}

        <div
          className="fixed top-0 left-0 w-full h-full opacity-[0.030]"
          style={{
            backgroundImage: "url('/noise.png')",
            backgroundRepeat: "repeat",
            backgroundSize: "auto",
            zIndex: -1,
          }}
        />
        <NavigationFrame/>

        {children}
      
        <Footer/>
      </body>
      </ThemeProvider>
    </html>
  );
}
